:-encoding(utf8).
allomorph(abartılı, adverb).
allomorph(abartısız, adverb).
allomorph(abdestli, adverb).
allomorph(abdestsiz, adverb).
allomorph(abes, adverb).
allomorph(aç, adverb).
allomorph(acaba, adverb).
allomorph(accelerando, adverb).
allomorph(acele, adverb).
allomorph(aceleten, adverb).
allomorph(acemice, adverb).
allomorph(acep, adverb).
allomorph(açık, adverb).
allomorph(açıkça, adverb).
allomorph(açıktan, adverb).
allomorph(acilen, adverb).
allomorph(acımasız, adverb).
allomorph(acımasızca, adverb).
allomorph(âcizane, adverb).
allomorph(adamakıllı, adverb).
allomorph(adamca, adverb).
allomorph(adamcasına, adverb).
allomorph(adedî, adverb).
allomorph(âdeta, adverb).
allomorph(adetçe, adverb).
allomorph(adilane, adverb).
allomorph(adımbaşı, adverb).
allomorph(adına, adverb).
allomorph(affettuoso, adverb).
allomorph(ağır, adverb).
allomorph(ağırca, adverb).
allomorph(agitato, adverb).
allomorph(ağızdan, adverb).
allomorph(ağrısız, adverb).
allomorph(ahbapça, adverb).
allomorph(aheste, adverb).
allomorph(ahir, adverb).
allomorph(ahiren, adverb).
allomorph(ahlakça, adverb).
allomorph(ahlaken, adverb).
allomorph(ahlaksızca, adverb).
allomorph(ahmakça, adverb).
allomorph(ailece, adverb).
allomorph(ailecek, adverb).
allomorph(akabinde, adverb).
allomorph(akıbet, adverb).
allomorph(akilane, adverb).
allomorph(akıllıca, adverb).
allomorph(aklen, adverb).
allomorph(aklınca, adverb).
allomorph(akşamdan, adverb).
allomorph(akşamları, adverb).
allomorph(akşamleyin, adverb).
allomorph(akşamüstü, adverb).
allomorph(akşamüzeri, adverb).
allomorph(aksine, adverb).
allomorph(aktarmalı, adverb).
allomorph(aktarmasız, adverb).
allomorph(alakart, adverb).
allomorph(alarga, adverb).
allomorph(alçakça, adverb).
allomorph(alelacele, adverb).
allomorph(alelhesap, adverb).
allomorph(alelhusus, adverb).
allomorph(alelıtlak, adverb).
allomorph(alelumum, adverb).
allomorph(alelusul, adverb).
allomorph(alenen, adverb).
allomorph(alessabah, adverb).
allomorph(âlimane, adverb).
allomorph(alkolsüz, adverb).
allomorph(allegretto, adverb).
allomorph(allegro, adverb).
allomorph(amabile, adverb).
allomorph(amansızca, adverb).
allomorph(amatörce, adverb).
allomorph(ambalajlı, adverb).
allomorph(ambalajsız, adverb).
allomorph(amirane, adverb).
allomorph(amirce, adverb).
allomorph(anaca, adverb).
allomorph(anafordan, adverb).
allomorph(anal, adverb).
allomorph(anasıl, adverb).
allomorph(anasız, adverb).
allomorph(anbean, adverb).
allomorph(andante, adverb).
allomorph(andantino, adverb).
allomorph(ani, adverb).
allomorph(anide, adverb).
allomorph(aniden, adverb).
allomorph(anif, adverb).
allomorph(animato, adverb).
allomorph(anında, adverb).
allomorph(anlaşılan, adverb).
allomorph(ansız, adverb).
allomorph(ansızın, adverb).
allomorph(antagonist, adverb).
allomorph(antrparantez, adverb).
allomorph(apansız, adverb).
allomorph(apansızın, adverb).
allomorph(apazlama, adverb).
allomorph(appassionato, adverb).
allomorph(aptalca, adverb).
allomorph(aptalcasına, adverb).
allomorph(arabasız, adverb).
allomorph(aracılığıyla, adverb).
allomorph(araçsız, adverb).
allomorph(aralıklı, adverb).
allomorph(aralıksız, adverb).
allomorph(aralıkta, adverb).
allomorph(arasız, adverb).
allomorph(ardınca, adverb).
allomorph(argolu, adverb).
allomorph(argosuz, adverb).
allomorph(arifane, adverb).
allomorph(ariyeten, adverb).
allomorph(arkadaşça, adverb).
allomorph(arsızca, adverb).
allomorph(artık, adverb).
allomorph(artistçe, adverb).
allomorph(aşağı, adverb).
allomorph(asaleten, adverb).
allomorph(âşıkane, adverb).
allomorph(aşikâre, adverb).
allomorph(aşırı, adverb).
allomorph(asırlarca, adverb).
allomorph(askerce, adverb).
allomorph(asla, adverb).
allomorph(aslanca, adverb).
allomorph(aslen, adverb).
allomorph(aslında, adverb).
allomorph(atfen, adverb).
allomorph(avanakça, adverb).
allomorph(avantadan, adverb).
allomorph(ayakta, adverb).
allomorph(ayaküstü, adverb).
allomorph(ayaküzeri, adverb).
allomorph(aybeay, adverb).
allomorph(ayık, adverb).
allomorph(aylık, adverb).
allomorph(aynen, adverb).
allomorph(aynıyla, adverb).
allomorph(ayrı, adverb).
allomorph(ayrıca, adverb).
allomorph(ayrıcasız, adverb).
allomorph(ayrıksız, adverb).
allomorph(ayrıyeten, adverb).
allomorph(az, adverb).
allomorph(azade, adverb).
allomorph(azca, adverb).
allomorph(azıcık, adverb).
allomorph(azimkârane, adverb).
allomorph(babacanca, adverb).
allomorph(badehu, adverb).
allomorph(badema, adverb).
allomorph(bahusus, adverb).
allomorph(bakarak, adverb).
allomorph(bakımdan, adverb).
allomorph(bakımından, adverb).
allomorph(balıklama, adverb).
allomorph(bana, adverb).
allomorph(banko, adverb).
allomorph(barbarca, adverb).
allomorph(bari, adverb).
allomorph(başarılı, adverb).
allomorph(başarısız, adverb).
allomorph(basbayağı, adverb).
allomorph(başıboş, adverb).
allomorph(başıkabak, adverb).
allomorph(basitçe, adverb).
allomorph(başkaca, adverb).
allomorph(başta, adverb).
allomorph(baştan, adverb).
allomorph(batsat, adverb).
allomorph(bayağı, adverb).
allomorph(bayramüstü, adverb).
allomorph(bayramüzeri, adverb).
allomorph(bazı, adverb).
allomorph(bedaheten, adverb).
allomorph(bedava, adverb).
allomorph(bedavadan, adverb).
allomorph(bedavasına, adverb).
allomorph(bedavaya, adverb).
allomorph(bedence, adverb).
allomorph(bedenen, adverb).
allomorph(begayet, adverb).
allomorph(behemehâl, adverb).
allomorph(beleşten, adverb).
allomorph(belki, adverb).
allomorph(bembeyaz, adverb).
allomorph(bence, adverb).
allomorph(bencilce, adverb).
allomorph(bencileyin, adverb).
allomorph(beraber, adverb).
allomorph(beraberce, adverb).
allomorph(beraberinde, adverb).
allomorph(bereket, adverb).
allomorph(berenarı, adverb).
allomorph(bermutat, adverb).
allomorph(bertafsil, adverb).
allomorph(besbelli, adverb).
allomorph(besmelesiz, adverb).
allomorph(beyhude, adverb).
allomorph(beyninde, adverb).
allomorph(biçimli, adverb).
allomorph(biçimsiz, adverb).
allomorph(bihakkın, adverb).
allomorph(bilahare, adverb).
allomorph(bilaistisna, adverb).
allomorph(bilakayduşart, adverb).
allomorph(bilakis, adverb).
allomorph(bilfiil, adverb).
allomorph(bilgece, adverb).
allomorph(bilgili, adverb).
allomorph(bilgince, adverb).
allomorph(bilhassa, adverb).
allomorph(bililtizam, adverb).
allomorph(bilistifade, adverb).
allomorph(bilmukabele, adverb).
allomorph(bilmünasebe, adverb).
allomorph(bilvasıta, adverb).
allomorph(binaen, adverb).
allomorph(binaenaleyh, adverb).
allomorph(binkat, adverb).
allomorph(binnetice, adverb).
allomorph(biperva, adverb).
allomorph(bir, adverb).
allomorph(biraz, adverb).
allomorph(birazcık, adverb).
allomorph(birden, adverb).
allomorph(birdenbire, adverb).
allomorph(birlikte, adverb).
allomorph(bitevi, adverb).
allomorph(biteviye, adverb).
allomorph(bittabi, adverb).
allomorph(bizatihi, adverb).
allomorph(bizce, adverb).
allomorph(bizcileyin, adverb).
allomorph(bizzat, adverb).
allomorph(bodoslamadan, adverb).
allomorph(bolca, adverb).
allomorph(bönce, adverb).
allomorph(boş, adverb).
allomorph(boşuna, adverb).
allomorph(boyca, adverb).
allomorph(boylamasına, adverb).
allomorph(böyle, adverb).
allomorph(böylece, adverb).
allomorph(böylecene, adverb).
allomorph(böylelikle, adverb).
allomorph(böylemesine, adverb).
allomorph(böylesine, adverb).
allomorph(boyuna, adverb).
allomorph(boyunca, adverb).
allomorph(budalacasına, adverb).
allomorph(bugünlerde, adverb).
allomorph(bugünlük, adverb).
allomorph(bunakça, adverb).
allomorph(bunca, adverb).
allomorph(bunsuz, adverb).
allomorph(bünyece, adverb).
allomorph(buracıkta, adverb).
allomorph(burada, adverb).
allomorph(buradan, adverb).
allomorph(burjuvaca, adverb).
allomorph(büsbütün, adverb).
allomorph(caba, adverb).
allomorph(cabadan, adverb).
allomorph(çabucacık, adverb).
allomorph(çabucak, adverb).
allomorph(çabuk, adverb).
allomorph(çabukça, adverb).
allomorph(çaçaronca, adverb).
allomorph(çağanak, adverb).
allomorph(çaktırmadan, adverb).
allomorph(çalakalem, adverb).
allomorph(çalakamçı, adverb).
allomorph(çalakaşık, adverb).
allomorph(çalakılıç, adverb).
allomorph(çalakürek, adverb).
allomorph(çalapaça, adverb).
allomorph(çalyaka, adverb).
allomorph(canavarca, adverb).
allomorph(candan, adverb).
allomorph(canice, adverb).
allomorph(canıgönülden, adverb).
allomorph(canıyürekten, adverb).
allomorph(cansiparane, adverb).
allomorph(cansız, adverb).
allomorph(çap, adverb).
allomorph(capcanlı, adverb).
allomorph(çapkınca, adverb).
allomorph(çapraz, adverb).
allomorph(çaprazlama, adverb).
allomorph(çaprazlamasına, adverb).
allomorph(çaprazvari, adverb).
allomorph(çarçabuk, adverb).
allomorph(carcur, adverb).
allomorph(çaresiz, adverb).
allomorph(çarnaçar, adverb).
allomorph(çarpıcı, adverb).
allomorph(çarpık, adverb).
allomorph(cartadak, adverb).
allomorph(cartadan, adverb).
allomorph(çatalsız, adverb).
allomorph(çaylakça, adverb).
allomorph(cebren, adverb).
allomorph(ceffelkalem, adverb).
allomorph(çehrece, adverb).
allomorph(çekingence, adverb).
allomorph(çekişmeli, adverb).
allomorph(çelebice, adverb).
allomorph(çelmece, adverb).
allomorph(ceman, adverb).
allomorph(cengâverce, adverb).
allomorph(çengüçağanak, adverb).
allomorph(centilmence, adverb).
allomorph(çepeçevre, adverb).
allomorph(cesurane, adverb).
allomorph(cesurca, adverb).
allomorph(cetbecet, adverb).
allomorph(çetince, adverb).
allomorph(cevaben, adverb).
allomorph(cevapsız, adverb).
allomorph(çevikçe, adverb).
allomorph(ceylanca, adverb).
allomorph(cidden, adverb).
allomorph(ciddi, adverb).
allomorph(cihangirane, adverb).
allomorph(cihetiyle, adverb).
allomorph(çıldırasıya, adverb).
allomorph(çılgıncasına, adverb).
allomorph(cimrice, adverb).
allomorph(çınsabah, adverb).
allomorph(çirkefçe, adverb).
allomorph(çirkince, adverb).
allomorph(cismen, adverb).
allomorph(çocukça, adverb).
allomorph(çoğun, adverb).
allomorph(çoğunlukla, adverb).
allomorph(çok, adverb).
allomorph(çokça, adverb).
allomorph(çoklarınca, adverb).
allomorph(çokluk, adverb).
allomorph(çoklukla, adverb).
allomorph(çoktan, adverb).
allomorph(cömertçe, adverb).
allomorph(coşkunca, adverb).
allomorph(cuk, adverb).
allomorph(cumhurca, adverb).
allomorph(cümleten, adverb).
allomorph(dâhice, adverb).
allomorph(dâhil, adverb).
allomorph(dâhilen, adverb).
allomorph(daim, adverb).
allomorph(daima, adverb).
allomorph(dakikane, adverb).
allomorph(dakikasında, adverb).
allomorph(dalgın, adverb).
allomorph(dalgündüz, adverb).
allomorph(dalkavukça, adverb).
allomorph(dalkılıç, adverb).
allomorph(damsız, adverb).
allomorph(dangadak, adverb).
allomorph(dar, adverb).
allomorph(darasız, adverb).
allomorph(decrescendo, adverb).
allomorph(defacto, adverb).
allomorph(defalarca, adverb).
allomorph(defaten, adverb).
allomorph(dehşetli, adverb).
allomorph(delice, adverb).
allomorph(delicesine, adverb).
allomorph(dembedem, adverb).
allomorph(demincek, adverb).
allomorph(deminden, adverb).
allomorph(deneysiz, adverb).
allomorph(derakap, adverb).
allomorph(derbederce, adverb).
allomorph(derhâl, adverb).
allomorph(derhatır, adverb).
allomorph(derinden, adverb).
allomorph(derinlemesine, adverb).
allomorph(derinliğine, adverb).
allomorph(derken, adverb).
allomorph(dertop, adverb).
allomorph(dervişane, adverb).
allomorph(dervişçe, adverb).
allomorph(despotça, adverb).
allomorph(devamlı, adverb).
allomorph(devce, adverb).
allomorph(devre, adverb).
allomorph(devren, adverb).
allomorph(dikçe, adverb).
allomorph(dikenlice, adverb).
allomorph(dikensiz, adverb).
allomorph(dikey, adverb).
allomorph(dikine, adverb).
allomorph(diklemesine, adverb).
allomorph(diktatörce, adverb).
allomorph(dimdik, adverb).
allomorph(diminuendo, adverb).
allomorph(dince, adverb).
allomorph(dinen, adverb).
allomorph(diplomatça, adverb).
allomorph(direkt, adverb).
allomorph(dışarı, adverb).
allomorph(doğaçlama, adverb).
allomorph(doğaçtan, adverb).
allomorph(doğallıkla, adverb).
allomorph(doğmaca, adverb).
allomorph(doğru, adverb).
allomorph(doğruca, adverb).
allomorph(doğrudan, adverb).
allomorph(doğrusu, adverb).
allomorph(dolayısıyla, adverb).
allomorph(dolaysız, adverb).
allomorph(doludizgin, adverb).
allomorph(domuzuna, adverb).
allomorph(dönüşümlü, adverb).
allomorph(dörtnala, adverb).
allomorph(doruklama, adverb).
allomorph(dosdoğru, adverb).
allomorph(dostane, adverb).
allomorph(dostça, adverb).
allomorph(doyasıya, adverb).
allomorph(düğünsüz, adverb).
allomorph(dünden, adverb).
allomorph(dünyada, adverb).
allomorph(düpedüz, adverb).
allomorph(duraksız, adverb).
allomorph(durmadan, adverb).
allomorph(durumca, adverb).
allomorph(duyguca, adverb).
allomorph(düzgün, adverb).
allomorph(ebediyen, adverb).
allomorph(ebesiz, adverb).
allomorph(edepli, adverb).
allomorph(edepsizce, adverb).
allomorph(edepsizcesine, adverb).
allomorph(edibane, adverb).
allomorph(efece, adverb).
allomorph(efendice, adverb).
allomorph(eğreti, adverb).
allomorph(eğri, adverb).
allomorph(ekmeksiz, adverb).
allomorph(ekseri, adverb).
allomorph(ekseriya, adverb).
allomorph(ekseriyetle, adverb).
allomorph(eksiksiz, adverb).
allomorph(ekstra, adverb).
allomorph(elan, adverb).
allomorph(elbet, adverb).
allomorph(elbette, adverb).
allomorph(elden, adverb).
allomorph(elhak, adverb).
allomorph(elhasıl, adverb).
allomorph(elinden, adverb).
allomorph(eliyle, adverb).
allomorph(elverdiğince, adverb).
allomorph(emaneten, adverb).
allomorph(emprovize, adverb).
allomorph(en, adverb).
allomorph(enayice, adverb).
allomorph(enayicesine, adverb).
allomorph(ender, adverb).
allomorph(enikonu, adverb).
allomorph(enlemesine, adverb).
allomorph(epey, adverb).
allomorph(epeyce, adverb).
allomorph(epeyi, adverb).
allomorph(epeyice, adverb).
allomorph(er, adverb).
allomorph(erce, adverb).
allomorph(ercecik, adverb).
allomorph(erkeksiz, adverb).
allomorph(erken, adverb).
allomorph(erkence, adverb).
allomorph(erkenden, adverb).
allomorph(esasen, adverb).
allomorph(esaslı, adverb).
allomorph(esefle, adverb).
allomorph(eşekçe, adverb).
allomorph(eskiden, adverb).
allomorph(eşkin, adverb).
allomorph(eşli, adverb).
allomorph(esnasında, adverb).
allomorph(etraflı, adverb).
allomorph(etraflıca, adverb).
allomorph(evce, adverb).
allomorph(evcek, adverb).
allomorph(evleviyetle, adverb).
allomorph(evvel, adverb).
allomorph(evvela, adverb).
allomorph(evvelce, adverb).
allomorph(evvelden, adverb).
allomorph(evvelemirde, adverb).
allomorph(evveli, adverb).
allomorph(evvelleri, adverb).
allomorph(ezberden, adverb).
allomorph(ezbere, adverb).
allomorph(ezcümle, adverb).
allomorph(ezgince, adverb).
allomorph(ezkaza, adverb).
allomorph(fakirce, adverb).
allomorph(faraza, adverb).
allomorph(farklıca, adverb).
allomorph(farzımuhal, adverb).
allomorph(fatihane, adverb).
allomorph(faullü, adverb).
allomorph(faulsüz, adverb).
allomorph(fazla, adverb).
allomorph(fazlaca, adverb).
allomorph(fazladan, adverb).
allomorph(fazlasıyla, adverb).
allomorph(fedaice, adverb).
allomorph(fehvasınca, adverb).
allomorph(fena, adverb).
allomorph(fettanca, adverb).
allomorph(fiilen, adverb).
allomorph(fikren, adverb).
allomorph(filhakika, adverb).
allomorph(filozofça, adverb).
allomorph(filvaki, adverb).
allomorph(fır, adverb).
allomorph(fırdolayı, adverb).
allomorph(fisebilillah, adverb).
allomorph(fıtraten, adverb).
allomorph(fizikçe, adverb).
allomorph(fondip, adverb).
allomorph(forte, adverb).
allomorph(fortepiano, adverb).
allomorph(fortissimo, adverb).
allomorph(fücceten, adverb).
allomorph(fütursuzca, adverb).
allomorph(fuzuli, adverb).
allomorph(gafilane, adverb).
allomorph(gâh, adverb).
allomorph(gâhi, adverb).
allomorph(gâhice, adverb).
allomorph(galiba, adverb).
allomorph(garanti, adverb).
allomorph(gâvurca, adverb).
allomorph(gâvurcasına, adverb).
allomorph(gayet, adverb).
allomorph(gayetle, adverb).
allomorph(gayri, adverb).
allomorph(gayrı, adverb).
allomorph(gayriihtiyari, adverb).
allomorph(geç, adverb).
allomorph(geççe, adverb).
allomorph(geçe, adverb).
allomorph(geçende, adverb).
allomorph(geçenlerde, adverb).
allomorph(genellikle, adverb).
allomorph(gepgenç, adverb).
allomorph(gerçekte, adverb).
allomorph(gerçekten, adverb).
allomorph(gerçi, adverb).
allomorph(gereğince, adverb).
allomorph(geri, adverb).
allomorph(gevşek, adverb).
allomorph(gibilerden, adverb).
allomorph(gibisinden, adverb).
allomorph(gıcıkça, adverb).
allomorph(giderayak, adverb).
allomorph(giderek, adverb).
allomorph(gine, adverb).
allomorph(gırla, adverb).
allomorph(gitgide, adverb).
allomorph(gittikçe, adverb).
allomorph(gıyaben, adverb).
allomorph(gıyabında, adverb).
allomorph(gizli, adverb).
allomorph(gizlice, adverb).
allomorph(gönlünce, adverb).
allomorph(gönüllüce, adverb).
allomorph(gönülsüz, adverb).
allomorph(gönülsüzce, adverb).
allomorph(görgüsüzce, adverb).
allomorph(görmece, adverb).
allomorph(görünürde, adverb).
allomorph(görünürlerde, adverb).
allomorph(görünüşte, adverb).
allomorph(güç, adverb).
allomorph(güçlükle, adverb).
allomorph(gücün, adverb).
allomorph(gümbedek, adverb).
allomorph(günahsız, adverb).
allomorph(günaşırı, adverb).
allomorph(günbegün, adverb).
allomorph(günde, adverb).
allomorph(gündüz, adverb).
allomorph(gündüzleri, adverb).
allomorph(gündüzün, adverb).
allomorph(günlerce, adverb).
allomorph(günübirliğine, adverb).
allomorph(günübirlik, adverb).
allomorph(güpegündüz, adverb).
allomorph(gürpedek, adverb).
allomorph(gürültüsüzce, adverb).
allomorph(güvensizce, adverb).
allomorph(güya, adverb).
allomorph(güzel, adverb).
allomorph(güzelce, adverb).
allomorph(güzellikle, adverb).
allomorph(güzün, adverb).
allomorph(haberli, adverb).
allomorph(habersiz, adverb).
allomorph(habersizce, adverb).
allomorph(haddizatında, adverb).
allomorph(hadisesiz, adverb).
allomorph(hafifçe, adverb).
allomorph(hafiften, adverb).
allomorph(haince, adverb).
allomorph(hakça, adverb).
allomorph(hakeza, adverb).
allomorph(hakikat, adverb).
allomorph(hakikaten, adverb).
allomorph(hakimane, adverb).
allomorph(hâkimane, adverb).
allomorph(hakkında, adverb).
allomorph(hakkıyla, adverb).
allomorph(haksızca, adverb).
allomorph(hâlen, adverb).
allomorph(hâlihazırda, adverb).
allomorph(halisane, adverb).
allomorph(hâliyle, adverb).
allomorph(hamaratça, adverb).
allomorph(hamilen, adverb).
allomorph(handiyse, adverb).
allomorph(hani, adverb).
allomorph(harfiyen, adverb).
allomorph(hariç, adverb).
allomorph(haricen, adverb).
allomorph(harrangürra, adverb).
allomorph(hart, adverb).
allomorph(hartadak, adverb).
allomorph(haşarıca, adverb).
allomorph(hasbelkader, adverb).
allomorph(hasbetenlillah, adverb).
allomorph(hasebiyle, adverb).
allomorph(hasılı, adverb).
allomorph(hasılıkelam, adverb).
allomorph(hasımca, adverb).
allomorph(hassaten, adverb).
allomorph(havadan, adverb).
allomorph(hayalen, adverb).
allomorph(hayâsızca, adverb).
allomorph(haybeden, adverb).
allomorph(haydi, adverb).
allomorph(haylazca, adverb).
allomorph(hayli, adverb).
allomorph(hayranlıkla, adverb).
allomorph(hayretle, adverb).
allomorph(haysiyetiyle, adverb).
allomorph(hazır, adverb).
allomorph(helal, adverb).
allomorph(helalinden, adverb).
allomorph(hemen, adverb).
allomorph(hemencecik, adverb).
allomorph(hep, adverb).
allomorph(hepten, adverb).
allomorph(hercaice, adverb).
allomorph(herhâlde, adverb).
allomorph(hesabına, adverb).
allomorph(hesapça, adverb).
allomorph(heyetiyle, adverb).
allomorph(hiç, adverb).
allomorph(hiçten, adverb).
allomorph(hilafsız, adverb).
allomorph(hilkaten, adverb).
allomorph(hımhım, adverb).
allomorph(hırsızlama, adverb).
allomorph(hitaben, adverb).
allomorph(hızla, adverb).
allomorph(hızlı, adverb).
allomorph(hodbehot, adverb).
allomorph(hödükçe, adverb).
allomorph(hoppaca, adverb).
allomorph(hoppadak, adverb).
allomorph(hoş, adverb).
allomorph(hoşça, adverb).
allomorph(hovardaca, adverb).
allomorph(hoyratça, adverb).
allomorph(hükmen, adverb).
allomorph(hukuken, adverb).
allomorph(hülasa, adverb).
allomorph(hülasaten, adverb).
allomorph(hunharca, adverb).
allomorph(hür, adverb).
allomorph(hürmeten, adverb).
allomorph(hürmetkârane, adverb).
allomorph(hürmetlice, adverb).
allomorph(hürmetsizce, adverb).
allomorph(hürya, adverb).
allomorph(hüsnüniyetle, adverb).
allomorph(hususi, adverb).
allomorph(hususuyla, adverb).
allomorph(iblisane, adverb).
allomorph(iblisçe, adverb).
allomorph(icabında, adverb).
allomorph(içeri, adverb).
allomorph(içinde, adverb).
allomorph(içkili, adverb).
allomorph(içkisiz, adverb).
allomorph(içre, adverb).
allomorph(içtenlikle, adverb).
allomorph(idarece, adverb).
allomorph(idareli, adverb).
allomorph(idareten, adverb).
allomorph(iğneleyici, adverb).
allomorph(ihtimal, adverb).
allomorph(ihtiyarsız, adverb).
allomorph(ihtiyaten, adverb).
allomorph(iken, adverb).
allomorph(ikindiüzeri, adverb).
allomorph(ikindiyin, adverb).
allomorph(iktidarsız, adverb).
allomorph(iktisaden, adverb).
allomorph(ilanen, adverb).
allomorph(ilanihaye, adverb).
allomorph(ilaveten, adverb).
allomorph(ilelebet, adverb).
allomorph(ileri, adverb).
allomorph(ileride, adverb).
allomorph(ilk, adverb).
allomorph(ilkelce, adverb).
allomorph(ilkten, adverb).
allomorph(illa, adverb).
allomorph(illaki, adverb).
allomorph(ille, adverb).
allomorph(imdi, adverb).
allomorph(inadına, adverb).
allomorph(incecikten, adverb).
allomorph(indinde, adverb).
allomorph(insafsızca, adverb).
allomorph(insanca, adverb).
allomorph(iptida, adverb).
allomorph(iptidaları, adverb).
allomorph(irsen, adverb).
allomorph(irticalen, adverb).
allomorph(işgüzarca, adverb).
allomorph(isli, adverb).
allomorph(ismen, adverb).
allomorph(isnaden, adverb).
allomorph(iştahlı, adverb).
allomorph(isteksiz, adverb).
allomorph(isteksizce, adverb).
allomorph(istinaden, adverb).
allomorph(istisnasız, adverb).
allomorph(itçe, adverb).
allomorph(itibaren, adverb).
allomorph(itibarıyla, adverb).
allomorph(itirazsız, adverb).
allomorph(ittifakla, adverb).
allomorph(ivedilikle, adverb).
allomorph(iyi, adverb).
allomorph(iyice, adverb).
allomorph(iyicene, adverb).
allomorph(iyilikle, adverb).
allomorph(izafeten, adverb).
allomorph(izansızca, adverb).
allomorph(izinsiz, adverb).
allomorph(kabaca, adverb).
allomorph(kabadayıca, adverb).
allomorph(kabala, adverb).
allomorph(kabilinden, adverb).
allomorph(kablelvuku, adverb).
allomorph(kaça, adverb).
allomorph(kaçak, adverb).
allomorph(kaçıkça, adverb).
allomorph(kadınsız, adverb).
allomorph(kafaca, adverb).
allomorph(kafadan, adverb).
allomorph(kâh, adverb).
allomorph(kala, adverb).
allomorph(kalantorca, adverb).
allomorph(kalben, adverb).
allomorph(kalender, adverb).
allomorph(kalenderce, adverb).
allomorph(kâmilen, adverb).
allomorph(kanalıyla, adverb).
allomorph(kancıkça, adverb).
allomorph(kanunen, adverb).
allomorph(kapıda, adverb).
allomorph(kararlama, adverb).
allomorph(kararlamadan, adverb).
allomorph(karşılıklı, adverb).
allomorph(karşılıksız, adverb).
allomorph(kaskatı, adverb).
allomorph(kasten, adverb).
allomorph(kasti, adverb).
allomorph(katbekat, adverb).
allomorph(kategorik, adverb).
allomorph(katı, adverb).
allomorph(katiyen, adverb).
allomorph(katiyetle, adverb).
allomorph(kavi, adverb).
allomorph(kavlince, adverb).
allomorph(kaypakça, adverb).
allomorph(kazaen, adverb).
allomorph(kazara, adverb).
allomorph(kazasız, adverb).
allomorph(kefaleten, adverb).
allomorph(kefenli, adverb).
allomorph(kefensiz, adverb).
allomorph(kelepçeli, adverb).
allomorph(kelepçesiz, adverb).
allomorph(kelimesiz, adverb).
allomorph(kemakân, adverb).
allomorph(kemiksiz, adverb).
allomorph(kendince, adverb).
allomorph(kendinden, adverb).
allomorph(kendisince, adverb).
allomorph(kerhen, adverb).
allomorph(kesin, adverb).
allomorph(kesinkes, adverb).
allomorph(kesinlikle, adverb).
allomorph(kesmece, adverb).
allomorph(kestirme, adverb).
allomorph(kestirmece, adverb).
allomorph(kestirmeden, adverb).
allomorph(keyfince, adverb).
allomorph(keza, adverb).
allomorph(kezalik, adverb).
allomorph(kibarca, adverb).
allomorph(kıçüstü, adverb).
allomorph(kıdemce, adverb).
allomorph(kılıcına, adverb).
allomorph(kılıçlama, adverb).
allomorph(kimileyin, adverb).
allomorph(kimsesiz, adverb).
allomorph(kimyaca, adverb).
allomorph(kıpırtısız, adverb).
allomorph(kirişleme, adverb).
allomorph(kırkyıl, adverb).
allomorph(kısa, adverb).
allomorph(kısaca, adverb).
allomorph(kısarak, adverb).
allomorph(kısıkça, adverb).
allomorph(kısıntılı, adverb).
allomorph(kıskıvrak, adverb).
allomorph(kısmen, adverb).
allomorph(kitapça, adverb).
allomorph(kıyasen, adverb).
allomorph(kıyasıya, adverb).
allomorph(kolay, adverb).
allomorph(kolayca, adverb).
allomorph(kolaycacık, adverb).
allomorph(kolaylıkla, adverb).
allomorph(kolektif, adverb).
allomorph(korakor, adverb).
allomorph(körcesine, adverb).
allomorph(korkusuzca, adverb).
allomorph(körlemeden, adverb).
allomorph(koşa, adverb).
allomorph(köşeleme, adverb).
allomorph(kötü, adverb).
allomorph(kudretten, adverb).
allomorph(kulaktan, adverb).
allomorph(külfetsizce, adverb).
allomorph(külliyen, adverb).
allomorph(kurnazca, adverb).
allomorph(kuşaklama, adverb).
allomorph(kuşkusuz, adverb).
allomorph(küskütük, adverb).
allomorph(küstahça, adverb).
allomorph(küttedek, adverb).
allomorph(kuvvetlice, adverb).
allomorph(laakal, adverb).
allomorph(lacerem, adverb).
allomorph(lafzen, adverb).
allomorph(lahzacık, adverb).
allomorph(lahzada, adverb).
allomorph(lakayıt, adverb).
allomorph(lappadak, adverb).
allomorph(larghetto, adverb).
allomorph(largo, adverb).
allomorph(larp, adverb).
allomorph(larpadak, adverb).
allomorph(laubali, adverb).
allomorph(laubalice, adverb).
allomorph(laubaliyane, adverb).
allomorph(layıkıyla, adverb).
allomorph(lebalep, adverb).
allomorph(legato, adverb).
allomorph(lento, adverb).
allomorph(levendane, adverb).
allomorph(loppadak, adverb).
allomorph(lüpten, adverb).
allomorph(lütfen, adverb).
allomorph(lütufkârane, adverb).
allomorph(lüzumsuzca, adverb).
allomorph(maada, adverb).
allomorph(maaile, adverb).
allomorph(maalesef, adverb).
allomorph(maalmemnuniye, adverb).
allomorph(maatteessüf, adverb).
allomorph(maddeten, adverb).
allomorph(maestoso, adverb).
allomorph(mağrurane, adverb).
allomorph(mağrurca, adverb).
allomorph(mağrurcasına, adverb).
allomorph(mahallece, adverb).
allomorph(mahcubane, adverb).
allomorph(mahcupça, adverb).
allomorph(mahfuzen, adverb).
allomorph(mahiye, adverb).
allomorph(mahkûmane, adverb).
allomorph(mahsuben, adverb).
allomorph(mahsus, adverb).
allomorph(mahsusen, adverb).
allomorph(mahzunane, adverb).
allomorph(mahzunca, adverb).
allomorph(makaslama, adverb).
allomorph(maksatlı, adverb).
allomorph(maksatsız, adverb).
allomorph(malca, adverb).
allomorph(malen, adverb).
allomorph(malulen, adverb).
allomorph(malum, adverb).
allomorph(mamafih, adverb).
allomorph(manaca, adverb).
allomorph(manen, adverb).
allomorph(mantıkça, adverb).
allomorph(mantıken, adverb).
allomorph(manyakça, adverb).
allomorph(marifetiyle, adverb).
allomorph(maskaraca, adverb).
allomorph(maskesiz, adverb).
allomorph(masrafsız, adverb).
allomorph(masumane, adverb).
allomorph(masumca, adverb).
allomorph(mealen, adverb).
allomorph(mebni, adverb).
allomorph(mecazen, adverb).
allomorph(mecburen, adverb).
allomorph(meccanen, adverb).
allomorph(mecnunane, adverb).
allomorph(mecnunca, adverb).
allomorph(melfufen, adverb).
allomorph(memnunca, adverb).
allomorph(memnuniyetle, adverb).
allomorph(mepsuten, adverb).
allomorph(merdane, adverb).
allomorph(merhameten, adverb).
allomorph(merhametsizce, adverb).
allomorph(merkezce, adverb).
allomorph(mertçe, adverb).
allomorph(mesabesinde, adverb).
allomorph(mesafeli, adverb).
allomorph(meşruten, adverb).
allomorph(mestane, adverb).
allomorph(mesudane, adverb).
allomorph(mesutça, adverb).
allomorph(metazori, adverb).
allomorph(mevkufen, adverb).
allomorph(mevsimlik, adverb).
allomorph(milim, adverb).
allomorph(milletçe, adverb).
allomorph(minnettarane, adverb).
allomorph(minnettarca, adverb).
allomorph(miskinane, adverb).
allomorph(miskince, adverb).
allomorph(mızmızca, adverb).
allomorph(moralman, adverb).
allomorph(motamot, adverb).
allomorph(muahharen, adverb).
allomorph(mucibince, adverb).
allomorph(muhakkak, adverb).
allomorph(muhtasaran, adverb).
allomorph(muhtemelen, adverb).
allomorph(mukabil, adverb).
allomorph(mukaddema, adverb).
allomorph(mükâfaten, adverb).
allomorph(mükemmelen, adverb).
allomorph(mükerreren, adverb).
allomorph(münasebetiyle, adverb).
allomorph(münavebeli, adverb).
allomorph(münferiden, adverb).
allomorph(münhasıran, adverb).
allomorph(muntazam, adverb).
allomorph(muntazaman, adverb).
allomorph(müphem, adverb).
allomorph(müreffehen, adverb).
allomorph(muslihane, adverb).
allomorph(müstacelen, adverb).
allomorph(müstakilen, adverb).
allomorph(müstemirren, adverb).
allomorph(müsteniden, adverb).
allomorph(müştereken, adverb).
allomorph(müstesna, adverb).
allomorph(müteakiben, adverb).
allomorph(müteakip, adverb).
allomorph(mütemadiyen, adverb).
allomorph(mütenekkiren, adverb).
allomorph(müteselsilen, adverb).
allomorph(müteveccihen, adverb).
allomorph(mutlak, adverb).
allomorph(mutlaka, adverb).
allomorph(mutluca, adverb).
allomorph(muttasıl, adverb).
allomorph(müttefiken, adverb).
allomorph(müttehiden, adverb).
allomorph(muvacehesinde, adverb).
allomorph(muvakkaten, adverb).
allomorph(muzafferane, adverb).
allomorph(muzafferce, adverb).
allomorph(muzipçe, adverb).
allomorph(naçizane, adverb).
allomorph(nadiren, adverb).
allomorph(nafile, adverb).
allomorph(nagehan, adverb).
allomorph(nakden, adverb).
allomorph(naklen, adverb).
allomorph(nakzen, adverb).
allomorph(namertçe, adverb).
allomorph(namıdiğer, adverb).
allomorph(namına, adverb).
allomorph(naşi, adverb).
allomorph(nasıl, adverb).
allomorph(nasılsa, adverb).
allomorph(nazaran, adverb).
allomorph(nazikâne, adverb).
allomorph(nazikçe, adverb).
allomorph(nazmen, adverb).
allomorph(ne, adverb).
allomorph(nece, adverb).
allomorph(nedametle, adverb).
allomorph(neden, adverb).
allomorph(nedeniyle, adverb).
allomorph(nedense, adverb).
allomorph(nedensiz, adverb).
allomorph(nehari, adverb).
allomorph(nerede, adverb).
allomorph(nereden, adverb).
allomorph(neredeyse, adverb).
allomorph(neresi, adverb).
allomorph(nereye, adverb).
allomorph(neşeli, adverb).
allomorph(nesren, adverb).
allomorph(neşren, adverb).
allomorph(neticeten, adverb).
allomorph(nevmit, adverb).
allomorph(neyse, adverb).
allomorph(nezaketen, adverb).
allomorph(nezdinde, adverb).
allomorph(nice, adverb).
allomorph(niçin, adverb).
allomorph(nihayet, adverb).
allomorph(nihayetinde, adverb).
allomorph(nikâhlı, adverb).
allomorph(nikâhsız, adverb).
allomorph(nispet, adverb).
allomorph(nispeten, adverb).
allomorph(nispetle, adverb).
allomorph(nite, adverb).
allomorph(niye, adverb).
allomorph(nöbetleşe, adverb).
allomorph(nobranca, adverb).
allomorph(noksansız, adverb).
allomorph(numerik, adverb).
allomorph(oburca, adverb).
allomorph(oburcasına, adverb).
allomorph(ödemeli, adverb).
allomorph(ödlekçe, adverb).
allomorph(öğlende, adverb).
allomorph(öğleüstü, adverb).
allomorph(öğleüzeri, adverb).
allomorph(öğleyin, adverb).
allomorph(oğulsuz, adverb).
allomorph(olasıya, adverb).
allomorph(ölçüsüz, adverb).
allomorph(oldukça, adverb).
allomorph(öldüresiye, adverb).
allomorph(ölesiye, adverb).
allomorph(olgunca, adverb).
allomorph(ömrübillah, adverb).
allomorph(ömrünce, adverb).
allomorph(ona, adverb).
allomorph(onca, adverb).
allomorph(önce, adverb).
allomorph(önceden, adverb).
allomorph(önceleri, adverb).
allomorph(öncelikle, adverb).
allomorph(onculayın, adverb).
allomorph(onlarca, adverb).
allomorph(onsuz, adverb).
allomorph(önünden, adverb).
allomorph(oracıkta, adverb).
allomorph(orada, adverb).
allomorph(oradan, adverb).
allomorph(oral, adverb).
allomorph(oranca, adverb).
allomorph(oranla, adverb).
allomorph(oraya, adverb).
allomorph(ortada, adverb).
allomorph(ortaklaşa, adverb).
allomorph(ortalama, adverb).
allomorph(ortalamasına, adverb).
allomorph(ortalıkta, adverb).
allomorph(örtülü, adverb).
allomorph(osmanlıca, adverb).
allomorph(otomatik, adverb).
allomorph(otomatikman, adverb).
allomorph(öyle, adverb).
allomorph(öylece, adverb).
allomorph(öylelikle, adverb).
allomorph(öylemesine, adverb).
allomorph(öylesine, adverb).
allomorph(oynakça, adverb).
allomorph(ozanca, adverb).
allomorph(özcesi, adverb).
allomorph(özellikle, adverb).
allomorph(özgürce, adverb).
allomorph(özürsüz, adverb).
allomorph(paraca, adverb).
allomorph(parasız, adverb).
allomorph(partizanca, adverb).
allomorph(patadak, adverb).
allomorph(patavatsızca, adverb).
allomorph(patronca, adverb).
allomorph(pattadak, adverb).
allomorph(pattadan, adverb).
allomorph(paytakça, adverb).
allomorph(pazarlıksız, adverb).
allomorph(pederane, adverb).
allomorph(pehlivanane, adverb).
allomorph(pehlivanca, adverb).
allomorph(pek, adverb).
allomorph(pekâlâ, adverb).
allomorph(pekçe, adverb).
allomorph(peltek, adverb).
allomorph(peşin, adverb).
allomorph(peşinatsız, adverb).
allomorph(peşinen, adverb).
allomorph(peyapey, adverb).
allomorph(peyderpey, adverb).
allomorph(peygamberane, adverb).
allomorph(peygamberce, adverb).
allomorph(peygambervari, adverb).
allomorph(pimpirikçe, adverb).
allomorph(pir, adverb).
allomorph(pısırıkça, adverb).
allomorph(pişkince, adverb).
allomorph(piyano, adverb).
allomorph(pratikte, adverb).
allomorph(presto, adverb).
allomorph(pürtelaş, adverb).
allomorph(rabıtasız, adverb).
allomorph(raddelerinde, adverb).
allomorph(rahat, adverb).
allomorph(rahîm, adverb).
allomorph(rahvan, adverb).
allomorph(randevulu, adverb).
allomorph(randevusuz, adverb).
allomorph(rappadak, adverb).
allomorph(rapten, adverb).
allomorph(rastgele, adverb).
allomorph(rastlantısal, adverb).
allomorph(resen, adverb).
allomorph(resmen, adverb).
allomorph(rezilce, adverb).
allomorph(rindane, adverb).
allomorph(rintçe, adverb).
allomorph(riyakârane, adverb).
allomorph(riyakârca, adverb).
allomorph(riyasız, adverb).
allomorph(ruhen, adverb).
allomorph(ruzuşeb, adverb).
allomorph(saadetle, adverb).
allomorph(saatinde, adverb).
allomorph(saatlerce, adverb).
allomorph(sabaha, adverb).
allomorph(sabahları, adverb).
allomorph(sabahleyin, adverb).
allomorph(sabahtan, adverb).
allomorph(sabırla, adverb).
allomorph(sabunsuz, adverb).
allomorph(sade, adverb).
allomorph(sadece, adverb).
allomorph(sadıkane, adverb).
allomorph(sadıkça, adverb).
allomorph(sadistçe, adverb).
allomorph(safça, adverb).
allomorph(safçasına, adverb).
allomorph(safi, adverb).
allomorph(sağlam, adverb).
allomorph(sağlamca, adverb).
allomorph(sağlıcakla, adverb).
allomorph(sahi, adverb).
allomorph(sahiden, adverb).
allomorph(şahsen, adverb).
allomorph(şakacıktan, adverb).
allomorph(şakadan, adverb).
allomorph(sakarca, adverb).
allomorph(şakasız, adverb).
allomorph(sakince, adverb).
allomorph(şakkadak, adverb).
allomorph(şakrak, adverb).
allomorph(salakça, adverb).
allomorph(salimen, adverb).
allomorph(salisen, adverb).
allomorph(sallapati, adverb).
allomorph(salt, adverb).
allomorph(samimi, adverb).
allomorph(samimiyetle, adverb).
allomorph(sana, adverb).
allomorph(sanatkârane, adverb).
allomorph(sanatkârca, adverb).
allomorph(şapadanak, adverb).
allomorph(saplantısız, adverb).
allomorph(saplı, adverb).
allomorph(şappadak, adverb).
allomorph(sarahaten, adverb).
allomorph(sarahatle, adverb).
allomorph(sargın, adverb).
allomorph(sarhoş, adverb).
allomorph(sarhoşça, adverb).
allomorph(sarsakça, adverb).
allomorph(şartınca, adverb).
allomorph(şaşı, adverb).
allomorph(şaşkınlıkla, adverb).
allomorph(savurganca, adverb).
allomorph(sayesinde, adverb).
allomorph(saygısızca, adverb).
allomorph(sayıca, adverb).
allomorph(saymaca, adverb).
allomorph(sebepsiz, adverb).
allomorph(sebepsizce, adverb).
allomorph(seçmece, adverb).
allomorph(sefihane, adverb).
allomorph(sefilane, adverb).
allomorph(sefilce, adverb).
allomorph(sehven, adverb).
allomorph(sek, adverb).
allomorph(şeklen, adverb).
allomorph(selamsız, adverb).
allomorph(sellemehüsselam, adverb).
allomorph(semizce, adverb).
allomorph(sence, adverb).
allomorph(seneye, adverb).
allomorph(şeran, adverb).
allomorph(serapa, adverb).
allomorph(serbest, adverb).
allomorph(serian, adverb).
allomorph(sermestane, adverb).
allomorph(sersefil, adverb).
allomorph(sersemce, adverb).
allomorph(serserice, adverb).
allomorph(sesli, adverb).
allomorph(sessiz, adverb).
allomorph(sessizce, adverb).
allomorph(sevabına, adverb).
allomorph(seyrek, adverb).
allomorph(şeytanca, adverb).
allomorph(seyyanen, adverb).
allomorph(şiddetle, adverb).
allomorph(şifahen, adverb).
allomorph(siftah, adverb).
allomorph(sigarasız, adverb).
allomorph(sık, adverb).
allomorph(sıkça, adverb).
allomorph(sıkı, adverb).
allomorph(sıkıca, adverb).
allomorph(silme, adverb).
allomorph(silmece, adverb).
allomorph(şimdicik, adverb).
allomorph(şimdiden, adverb).
allomorph(şimdilerde, adverb).
allomorph(şimdileyin, adverb).
allomorph(sinsice, adverb).
allomorph(şıppadak, adverb).
allomorph(şipşak, adverb).
allomorph(şırakkadak, adverb).
allomorph(sırasıyla, adverb).
allomorph(sırdaşça, adverb).
allomorph(sırf, adverb).
allomorph(sırtüstü, adverb).
allomorph(sittinsene, adverb).
allomorph(sıvama, adverb).
allomorph(sıvırya, adverb).
allomorph(siyaseten, adverb).
allomorph(sizce, adverb).
allomorph(sızıltılı, adverb).
allomorph(sızıltısız, adverb).
allomorph(softaca, adverb).
allomorph(soğuk, adverb).
allomorph(soğukça, adverb).
allomorph(sokulu, adverb).
allomorph(soluksuz, adverb).
allomorph(sonra, adverb).
allomorph(sonradan, adverb).
allomorph(sonraları, adverb).
allomorph(sonunda, adverb).
allomorph(sorgusuz, adverb).
allomorph(şorolop, adverb).
allomorph(şövalyece, adverb).
allomorph(şöyle, adverb).
allomorph(şöylece, adverb).
allomorph(şöylemesine, adverb).
allomorph(şöylesine, adverb).
allomorph(soysuzca, adverb).
allomorph(sözce, adverb).
allomorph(sözde, adverb).
allomorph(sözleşmeli, adverb).
allomorph(sözleşmesiz, adverb).
allomorph(suçüstü, adverb).
allomorph(sularında, adverb).
allomorph(şunca, adverb).
allomorph(şuracıkta, adverb).
allomorph(şurada, adverb).
allomorph(süratle, adverb).
allomorph(sürekli, adverb).
allomorph(süresiz, adverb).
allomorph(sureta, adverb).
allomorph(sürgit, adverb).
allomorph(suskun, adverb).
allomorph(suspus, adverb).
allomorph(susuz, adverb).
allomorph(ta, adverb).
allomorph(taammüden, adverb).
allomorph(taban, adverb).
allomorph(tabanvay, adverb).
allomorph(tabi, adverb).
allomorph(tabiatıyla, adverb).
allomorph(tabii, adverb).
allomorph(tahminen, adverb).
allomorph(tahriren, adverb).
allomorph(takiben, adverb).
allomorph(takipsiz, adverb).
allomorph(takkadak, adverb).
allomorph(takriben, adverb).
allomorph(tam, adverb).
allomorph(tamamen, adverb).
allomorph(tamamıyla, adverb).
allomorph(taptaze, adverb).
allomorph(tasasız, adverb).
allomorph(taşımlık, adverb).
allomorph(tatlı, adverb).
allomorph(tatlıca, adverb).
allomorph(tatlılıkla, adverb).
allomorph(tatsız, adverb).
allomorph(teberrüken, adverb).
allomorph(tedarikli, adverb).
allomorph(tedariksiz, adverb).
allomorph(tedbirli, adverb).
allomorph(tedbirsiz, adverb).
allomorph(tedricen, adverb).
allomorph(tedviren, adverb).
allomorph(tehirli, adverb).
allomorph(tehirsiz, adverb).
allomorph(tek, adverb).
allomorph(tekdüze, adverb).
allomorph(tekiden, adverb).
allomorph(teklifsiz, adverb).
allomorph(teklifsizce, adverb).
allomorph(tekrar, adverb).
allomorph(tekraren, adverb).
allomorph(telaşsız, adverb).
allomorph(telmihen, adverb).
allomorph(temelli, adverb).
allomorph(temelsiz, adverb).
allomorph(temiz, adverb).
allomorph(temkinlice, adverb).
allomorph(tepeleme, adverb).
allomorph(tepetakla, adverb).
allomorph(tepeüstü, adverb).
allomorph(terbiyesizce, adverb).
allomorph(terbiyesizcesine, adverb).
allomorph(tercihen, adverb).
allomorph(tereddütsüz, adverb).
allomorph(terfian, adverb).
allomorph(tersine, adverb).
allomorph(tertipli, adverb).
allomorph(tertipsiz, adverb).
allomorph(tesadüfen, adverb).
allomorph(tevekkeli, adverb).
allomorph(tevfikan, adverb).
allomorph(tez, adverb).
allomorph(tezce, adverb).
allomorph(tezelden, adverb).
allomorph(tıbben, adverb).
allomorph(tıngadak, adverb).
allomorph(tıpatıp, adverb).
allomorph(tıpkı, adverb).
allomorph(titizlikle, adverb).
allomorph(top, adverb).
allomorph(topyekûn, adverb).
allomorph(torpilsiz, adverb).
allomorph(töskürü, adverb).
allomorph(tükenik, adverb).
allomorph(tümden, adverb).
allomorph(türkçesi, adverb).
allomorph(tutturabildiğine, adverb).
allomorph(tutuksuz, adverb).
allomorph(ucuzca, adverb).
allomorph(ucuzuna, adverb).
allomorph(uğrun, adverb).
allomorph(uğrunda, adverb).
allomorph(ümmetçe, adverb).
allomorph(umumiyetle, adverb).
allomorph(üniformalı, adverb).
allomorph(üniformasız, adverb).
allomorph(upuzun, adverb).
allomorph(ürkekçe, adverb).
allomorph(usangın, adverb).
allomorph(uslu, adverb).
allomorph(ustaca, adverb).
allomorph(üstadane, adverb).
allomorph(ustalıkla, adverb).
allomorph(üstatça, adverb).
allomorph(üste, adverb).
allomorph(üstten, adverb).
allomorph(üstüne, adverb).
allomorph(üstünkörü, adverb).
allomorph(usul, adverb).
allomorph(usulca, adverb).
allomorph(usulcacık, adverb).
allomorph(usuldan, adverb).
allomorph(usullacık, adverb).
allomorph(utanmazca, adverb).
allomorph(uyarınca, adverb).
allomorph(uykulu, adverb).
allomorph(uykusuz, adverb).
allomorph(uzaktan, adverb).
allomorph(üzengisiz, adverb).
allomorph(üzerinde, adverb).
allomorph(üzerine, adverb).
allomorph(uzun, adverb).
allomorph(uzunca, adverb).
allomorph(uzunlamasına, adverb).
allomorph(üzüntülü, adverb).
allomorph(üzüntüsüz, adverb).
allomorph(vahşiyane, adverb).
allomorph(vakıa, adverb).
allomorph(vakitçe, adverb).
allomorph(vaktinde, adverb).
allomorph(vaktiyle, adverb).
allomorph(vaktizamanında, adverb).
allomorph(vasıtasıyla, adverb).
allomorph(vehleten, adverb).
allomorph(vekâleten, adverb).
allomorph(velhasıl, adverb).
allomorph(velhasılıkelam, adverb).
allomorph(veresiye, adverb).
allomorph(verevine, adverb).
allomorph(vicahen, adverb).
allomorph(vicdanen, adverb).
allomorph(vira, adverb).
allomorph(vücutça, adverb).
allomorph(vurtut, adverb).
allomorph(yakında, adverb).
allomorph(yakından, adverb).
allomorph(yakinen, adverb).
allomorph(yakınlarda, adverb).
allomorph(yalancıktan, adverb).
allomorph(yalandan, adverb).
allomorph(yalansız, adverb).
allomorph(yalapşap, adverb).
allomorph(yalnızca, adverb).
allomorph(yan, adverb).
allomorph(yani, adverb).
allomorph(yanında, adverb).
allomorph(yanlamasına, adverb).
allomorph(yanlış, adverb).
allomorph(yanlışlıkla, adverb).
allomorph(yapayalnız, adverb).
allomorph(yapyakın, adverb).
allomorph(yaradılıştan, adverb).
allomorph(yârence, adverb).
allomorph(yarı, adverb).
allomorph(yarımşar, adverb).
allomorph(yaşamaca, adverb).
allomorph(yavaş, adverb).
allomorph(yavaşça, adverb).
allomorph(yavaşçacık, adverb).
allomorph(yavuzca, adverb).
allomorph(yaya, adverb).
allomorph(yayan, adverb).
allomorph(yedekte, adverb).
allomorph(yekpare, adverb).
allomorph(yekten, adverb).
allomorph(yekvücut, adverb).
allomorph(yengeçvari, adverb).
allomorph(yeni, adverb).
allomorph(yenice, adverb).
allomorph(yeniden, adverb).
allomorph(yenilerde, adverb).
allomorph(yerinde, adverb).
allomorph(yerine, adverb).
allomorph(yeterince, adverb).
allomorph(yevmiye, adverb).
allomorph(yıllarca, adverb).
allomorph(yollu, adverb).
allomorph(yoluyla, adverb).
allomorph(yosmaca, adverb).
allomorph(yukarı, adverb).
allomorph(yukarıda, adverb).
allomorph(yukarıdan, adverb).
allomorph(yüklüce, adverb).
allomorph(yüksek, adverb).
allomorph(yumuşakça, adverb).
allomorph(yüreklilikle, adverb).
allomorph(yüzbeyüz, adverb).
allomorph(yüzden, adverb).
allomorph(yüzlemece, adverb).
allomorph(yüzleşmece, adverb).
allomorph(yüzükoyun, adverb).
allomorph(yüzünden, adverb).
allomorph(yüzüstü, adverb).
allomorph(yüzyıllarca, adverb).
allomorph(zahir, adverb).
allomorph(zahirde, adverb).
allomorph(zahiren, adverb).
allomorph(zahmetsizce, adverb).
allomorph(zalimane, adverb).
allomorph(zalimce, adverb).
allomorph(zamanında, adverb).
allomorph(zamanla, adverb).
allomorph(zamansız, adverb).
allomorph(zararına, adverb).
allomorph(zarfında, adverb).
allomorph(zarifane, adverb).
allomorph(zarifçe, adverb).
allomorph(zaten, adverb).
allomorph(zati, adverb).
allomorph(zecren, adverb).
allomorph(zekice, adverb).
allomorph(zevzekçe, adverb).
allomorph(zihince, adverb).
allomorph(zihnen, adverb).
allomorph(zımnen, adverb).
allomorph(zımnında, adverb).
allomorph(zıngadak, adverb).
allomorph(zinhar, adverb).
allomorph(zıppadak, adverb).
allomorph(zirzopça, adverb).
allomorph(ziyadesiyle, adverb).
allomorph(zor, adverb).
allomorph(zorca, adverb).
allomorph(zorla, adverb).
allomorph(zorlukla, adverb).
